### ISSUE TITLE
Errors in reactions

### ISSUE THREAD

**Issue by kate-fie** [kate-fie/syndirella#52]
@mwinokan has pointed out examples of synthesis route errors in [this issue](https://github.com/mwinokan/HIPPO/issues/94#issue-2272434775). 

Things to check/Fix/Implement:

- [x] All deprotection SMARTS
- [x] Exact number of atom removal expected for deprotections (implemented with [hippo.chem](https://github.com/mwinokan/HIPPO/blob/main/hippo/chem.py))
- [x] Not elaborating on protection groups (which should be fixed when the SMARTS are exact)
- [ ] Check if reactant can be both reactants in given rxn --> flag

Inchi key uniqueness check after doing any reaction (EDIT: not priority because I'm already checking for duplicates)

I also [read](https://github.com/rdkit/rdkit-tutorials/blob/46b3a615e4b9aa8ebbc99dc587d55fe8af168d5a/notebooks/003_SMARTS_ReactionsExamples.ipynb) that products from this command are not sanitised...

- [x] Add sanitisation step after getting products in SlipperSynthesizer

**Comment by kate-fie** [comment]
I noticed with `rxn.RunReactants` that multiple of the same products can be output. Need to check why this is the case. 

I also [read](https://github.com/rdkit/rdkit-tutorials/blob/46b3a615e4b9aa8ebbc99dc587d55fe8af168d5a/notebooks/003_SMARTS_ReactionsExamples.ipynb) that products from this command are not sanitised...

- [ ] Add sanitisation step after getting products in SlipperSynthesizer

**Comment by mwinokan** [comment]
@kate-fie I have implemented checks to catch most of the invalid reactions (see [hippo.chem](https://github.com/mwinokan/HIPPO/blob/main/hippo/chem.py))

I hope you can help prevent the following types of duplicates:

<img width="693" alt="Screenshot 2024-04-30 at 21 57 59" src="https://github.com/kate-fie/syndirella/assets/36866506/e73c05e6-b886-4841-a5d4-391aac7c4097">

**Comment by kate-fie** [comment]
> I noticed with `rxn.RunReactants` that multiple of the same products can be output. Need to check why this is the case.

Multiple products should only be returned if the SMARTS matches more than once in the reactant, this is not the case for this N-boc deprotection:

```python
with open('/base_path/RXN_SMARTS_CONSTANTS.json') as f:
    reaction_smarts = json.load(f)

def run_reaction(rxn_smarts, mol_smiles):
    rxn = Chem.rdChemReactions.ReactionFromSmarts(rxn_smarts)
    mol = Chem.MolFromSmiles(mol_smiles)
    display(Draw.ReactionToImage(rxn))
    products = rxn.RunReactants((mol,))
    display(Draw.MolToImage(mol))
    if len(products) == 0:
        display('No products')
    else:
        product_images = [Draw.MolToImage(p[0]) for p in products]
        display(product_images[0])
    return products

run_reaction(reaction_smarts['N-Boc_deprotection'], 'CC(C)NC(=O)OC(C)(C)C(=O)Nc1c(NC(=O)OC(C)(C)C)cnn1C')
```

![image](https://github.com/kate-fie/syndirella/assets/77400066/e71ab5cf-903b-4602-9e42-3a80ad696dcf)
Reactant:
![image](https://github.com/kate-fie/syndirella/assets/77400066/f21231f1-71b1-4b86-9253-9974c0b04852)
Exact product returned 6 times:
![image](https://github.com/kate-fie/syndirella/assets/77400066/d3a19e7f-974e-42a4-bf9b-a3cf0f35cf32)

Therefore I'm just going to return the unique products with this:
```python
def unique_molecules_by_inchi(mol_list):
    seen = set()  # A set to store unique InChI keys
    unique_mols = []  # List to store unique molecules
    for mol in mol_list:
        if mol is None:
            continue
        # Generate the InChI key for the molecule
        inchi_key = inchi.MolToInchiKey(mol)
        if inchi_key not in seen:
            print(inchi_key)
            seen.add(inchi_key)
            unique_mols.append(mol)
    return unique_mols
```

Which when ran on this example isn't too long:
```python
%timeit unique_molecules_by_inchi(products)

> 493 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

If there are 20,000 reactions to perform it would take 10 s overall.

**Comment by kate-fie** [comment]
N-boc deprotection updated to be more specific. 

![image](https://github.com/kate-fie/syndirella/assets/77400066/5843a2fc-8289-41f9-8c77-7b09e1cc941d)

**Comment by kate-fie** [comment]
**Benzyl alcohol deprotection**

Previous: `[#8&X2:2]-[#6]-[c]1[c][c][c][c][c]1>>[#8&X2:2]`
![image](https://github.com/kate-fie/syndirella/assets/77400066/2cb044b0-28dd-4b27-9daf-a4164baa0e19)

Updated: `[#8&X2:2]-[#6&H2]-[c]1[c&H1][c&H1][c&H1][c&H1][c&H1]1>>[#8&X2:2]`
![image](https://github.com/kate-fie/syndirella/assets/77400066/a2a613d4-3b28-4c03-884f-39d4da16b5b0)

**Comment by kate-fie** [comment]
N Bn deprotection (Bn = Benzyl)

Previous: `[#7&X3:2]-[#6]-[cR1]1[cR1][cR1][cR1][cR1][cR1]1>>[#7&X3:2]`
![image](https://github.com/kate-fie/syndirella/assets/77400066/e8827401-1fe0-4893-83a7-1dcb3da60788)

Updated: `[#7&X3:2]-[#6&H2]-[c]1[c&H1][c&H1][c&H1][c&H1][c&H1]1>>[#7&X3:2]`
![image](https://github.com/kate-fie/syndirella/assets/77400066/7ab74904-5bfb-4a91-98d2-1346139a096d)

**Comment by kate-fie** [comment]
**TBS alcohol deprotection** 

Previous: `[#6:1]-[#8:2]-[#14](-[#6])(-[#6])-[#6](-[#6])(-[#6])(-[#6])>>[#6:1]-[#8:2]`
![image](https://github.com/kate-fie/syndirella/assets/77400066/b6d102d7-3385-4233-9f9d-84a5d1eea9ef)

Updated: `[#6:1]-[#8&H0:2]-[#14](-[#6&H3])(-[#6&H3])-[#6](-[#6&H3])(-[#6&H3])(-[#6&H3])>>[#6:1]-[#8:2]`
![image](https://github.com/kate-fie/syndirella/assets/77400066/ec7753ba-1be6-44f3-8de7-e47397a78e7c)

**Comment by kate-fie** [comment]
These have been figured out for now.
